image: debovema/docker-mvn:3.5.4

test:
    script:
        - mvn clean deploy -P t3-snapshot
    except:
        - tags

site:
    script:
        - mvn clean site-deploy -P t3-snapshot
    except:
        - tags

site-redeploy:
    script:
        - mvn clean site-deploy -P t3-archive
        - mvn clean site-deploy -P t3-release
    only:
        - tags

mirror:
    script:
        - "sh -c '$(curl -H \'PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN\' -fsSL https://git.teecu.be/api/v4/projects/19/repository/files/mirror-repository-to-github.sh/raw?ref=master)'"
